# Basic arguments
work_dir: '/home/yanghao/rubbish/vrdual_test_3'

# Processor
gpus: 1
num_epoch: 3

# Debug
seed: 325
eval_interval: 1

# Data
root: '/home/yanghao/data/HKU/hku_skeleton_25'
root2: /home/yanghao/data/HKU/hku_skeleton_25/gcn_video_features
dataset: '' # Path to the generated visual features
dataloader: 'hku'
split: 5
data_type: 'full'
oversample_vr: False
batch_size: 16

# Model
model_name: 'vrdual'
lr: 1e-4
model_args:
  input_size: 256
  hidden_size :  512
  output_size: 100
  emb_dim :  512
  n_hidden_layers: 0
  visual_dim: 768

# Ablation
activate_train: True
test_p: False
resume: False
        
