Experiment_name: ntu_ShiftGCN_joint_xview

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: /home/yanghao/data/HKU/hku_skeleton_25/processed/all_data_joint.npy
  label_path: /home/yanghao/data/HKU/hku_skeleton_25/processed/all_label.pkl
  filename_path: /home/yanghao/data/HKU/hku_skeleton_25/processed/all_filenames.pkl
  video_path: /home/yanghao/data/HKU/hku_skeleton_25/video
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: /home/yanghao/data/HKU/hku_skeleton_25/processed/all_data_joint.npy
  label_path: /home/yanghao/data/HKU/hku_skeleton_25/processed/all_label.pkl

# model
model: model.shift_gcn.Model
weights: /home/yanghao/SummerRA/Code/ZSAR/Shift-GCN/save_models/ntu_ShiftGCN_joint_xview.pt
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  # graph: graph.hku.Graph
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.001
step: [60, 80, 100]

# training
device: [0]
only_train_epoch: 1
batch_size: 16
test_batch_size: 16
num_epoch: 1

# saving
feature_output_dir: /home/yanghao/data/HKU/hku_skeleton_25/gcn_video_features